### ISSUE TITLE
GraphQL endpoint

### ISSUE THREAD

**Issue by dimkinv** [myspecialway/my-special-way-web#7]
Create graphQL endpoint for models

**Comment by ah584d** [comment]
i started working on it, let me know if i can commit the code in the client

**Comment by dimkinv** [comment]
OK. So can you please assign it to yourself and move it to in progress state?
 
As for committing, just create a branch and work there, you can commit whatever you want there without affecting the master

**Comment by dimkinv** [comment]
Closing as it's a duplicate
